spring:
  application:
    name: eduteach
  datasource:
    url: jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
    username: 9a82b9da326f9893870c6e9237b866d896231a1a1de439b9b784a9b3bbc1a865
    password: sk_UXYmDmuGuBX6-eo4Vgj7h
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: your-256-bit-secret-key-for-jwt-token-generation-must-be-long-enough
  expiration: 86400000

server:
  port: 8080